import html from './html.webp'
import js from './js.png'
import reactIcon from './react.png'
import Aya from './Aya.jpg'
import css from './css.png'
import gmail from './gmail.png'
import github from './github.png'
import Git from './Git.png'
import front from './front.png'
import tool from './tool.png'
import softSkills from './softSkills.png'
import Aya_jouney_CV from './Aya Jouney - Front-End Developer - Resume.pdf'
import Do from './Document.png'
import dr_portfolio from './dr_portfolio.png'
import Gpt from './Gpt.png'
import  JS_Slider from './JS_SLider.png'
import Genome from './Genome.png'
import Kasper from './Kasper.png'
import Index from './Index.png'
import LeonOne from './LeonOne.png'
import medical from './Medical_School.png'
import carDealer from './Car Dealer.png'
export {medical,Index,carDealer,Do,dr_portfolio,Gpt,JS_Slider,Genome,Kasper,LeonOne,html,js,reactIcon,Aya,css,gmail,Git,github,front,tool,softSkills,Aya_jouney_CV};