import html from './html.webp'
import js from './js.png'
import reactIcon from './react.png'
import Aya from './Aya.jpg'
import css from './css.png'
import gmail from './gmail.png'
import github from './github.png'
import Git from './Git.png'
import front from './front.png'
import tool from './tool.png'
import softSkills from './softSkills.png'
import Aya_jouney_CV from './Aya_Jouney_CV.pdf'
export {html,js,reactIcon,Aya,css,gmail,Git,github,front,tool,softSkills,Aya_jouney_CV};